name: Deploy to Development

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build for development
        run: npm run build:dev

      - name: Setup Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate to Firebase
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}' > $HOME/firebase-service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-service-account.json
          firebase use picking-cds-ar --token ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy to Firebase Development
        run: firebase deploy --only hosting:development --token ${{ secrets.FIREBASE_TOKEN }}
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-service-account.json

      - name: Clean up service account file
        run: rm -f $HOME/firebase-service-account.json
