name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
pm           node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build for production
        run: |
          npm run build -- --configuration production
        env:
          NODE_ENV: production

      - name: Deploy to Firebase Production
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PICKING_CDS_AR }}"
          projectId: picking-cds-ar
